on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        fetch-depth: 0
        persist-credentials: false

      - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16
            registry-url: 'https://npm.pkg.github.com'
          env:
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
        shell: bash

      - name: Build code
        run: |
          npm run build
        shell: bash

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @saithodev/semantic-release-backmerge
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'main',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
