on:
  workflow_call:
    inputs:
      AWS_DEPLOY_REGION:
        required: false
        type: string
        default: 'eu-west-1'
      domain:
        required: true
        type: string
      team:
        required: true
        type: string
      node-version:
        type: number
        required: false
        default: 16
      sam-template-file:
        type: string
        required: false
        default: ''
      sam-config-file:
        type: string
        required: false
        default: ''
      accountName:
        type: string
        required: false
        default: ''
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      AWS_CICD_ACCOUNT:
        required: true
      AWS_CICD_API_URL:
        required: true
      AWS_CICD_API_REGION:
        required: true
    outputs:
      account:
        description: 'Account that was deployed to'
        value: ${{ jobs.Account.outputs.account }}
      environment:
        description: 'Environment that was deployed to'
        value: ${{ jobs.Account.outputs.environment }}

jobs:
  Account:
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: 'github-actions-oidc-session'
      accountName: ${{ inputs.accountName }}
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Release:
    needs: [Account]
    uses: ./.github/workflows/step-release-aws.yml
    with:
      domain: ${{ inputs.domain }}
      team: ${{ inputs.team }}
      environment: ${{ needs.Account.outputs.environment }}
      AWS_DEPLOY_REGION: ${{ inputs.AWS_DEPLOY_REGION }}
      node-version: ${{ inputs.node-version }}
      sam-template-file: ${{ inputs.sam-template-file }}
      sam-config-file: ${{ inputs.sam-config-file }}
    secrets:
      AWS_CICD_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
