on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      node-version:
        type: number
        required: false
        default: 18
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      SEMANTIC_RELEASE_TOKEN:
        required: true
      AWS_CICD_ACCOUNT:
        required: true
      AWS_CICD_API_URL:
        required: true
      AWS_CICD_API_REGION:
        required: true

jobs:
  Account:
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: 'github-actions-oidc-session'
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Test:
    needs: [Account]
    uses: ./.github/workflows/step-test-deploy.yml
    with:
      domain: ${{ inputs.domain }}
      node-version: ${{ inputs.node-version }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
      AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Release:
    needs: [Test]
    uses: ./.github/workflows/step-release-gh-package.yml
    with:
      node-version: ${{ inputs.node-version }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
