on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      team:
        required: true
        type: string
      environment:
        required: true
        type: string
      AWS_DEPLOY_REGION:
        required: true
        type: string
      run-command:
        type: string
        description: 'npm run command to run before sam build'
        required: false
      node-version:
        type: number
        required: false
        default: 16
      sam-template-file:
        type: string
        required: false
        default: ''
      sam-config-file:
        type: string
        required: false
        default: ''
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_CICD_API_REGION:
        required: true
      NODE_AUTH_TOKEN:
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: npm run command (if specified)
        if: ${{ inputs.run-command }}
        run: |
          npm ci --ignore-scripts
          npm run ${{ inputs.run-command }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-actions
          role-session-name: github-actions-oidc-session
          aws-region: ${{ secrets.AWS_CICD_API_REGION }}
      - name: Build
        shell: bash
        run: |
          if [ ! -z "${{ inputs.sam-template-file }}" ]
          then
              template_file_param="--template-file ${{ inputs.sam-template-file }}"
          else
              template_file_param=""
          fi
          if [ ! -z "${{ inputs.sam-config-file }}" ]
          then
              config_file_param="--config-file ${{ inputs.sam-config-file }}"
          else
              config_file_param=""
          fi          
          sam build \
          --parallel \
          $config_file_param \
          --config-env ${{ inputs.environment }} \
          $template_file_param
      - name: Deploy
        shell: bash
        run: |
          if [ ! -z "${{ inputs.sam-template-file }}" ]
          then
              template_file_param="--template-file ${{ inputs.sam-template-file }}"
          else
              template_file_param=""
          fi
          if [ ! -z "${{ inputs.sam-config-file }}" ]
          then
              config_file_param="--config-file ${{ inputs.sam-config-file }}"
          else
              config_file_param=""
          fi               
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name ${{ github.event.repository.name }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region ${{ inputs.AWS_DEPLOY_REGION }} \
          --s3-prefix ${{ github.event.repository.name }} \
          --resolve-s3 \
          config_file_param \
          --config-env ${{ inputs.environment }} \
          --tags \
            'domain=${{ inputs.domain }} \
            team=${{ inputs.team }}' \
          $template_file_param 
