on:
  workflow_call:
    inputs:
      audit_level:
        type: string
        required: false
        default: low
      node-version:
        type: number
        required: false
        default: 16
    secrets:
      NODE_AUTH_TOKEN:
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  Check-Security-Audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci --ignore-scripts
        shell: bash

      - name: Run Security Audit
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: ${{ inputs.audit_level }}
          create_issues: false
          create_pr_comments: false
          # github_token: ${{ secrets.GITHUB_TOKEN }} # this is specified as required for "oke-py/npm-audit-action", but seems to work well enough without it - only practical difference is that it won't comment on the PR
