on:
  workflow_call:
    inputs:
      DISTRIBUTION_ID:
        type: string
        required: true
      PATHS_TO_INVALIDATE:
        type: string
        required: false
        default: "/*"
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_CICD_API_REGION:
        required: true

jobs:
  CreateInvalidation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-actions
          role-session-name: github-actions-oidc-session
          aws-region: ${{ secrets.AWS_CICD_API_REGION }}
      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.DISTRIBUTION_ID }} --paths '${{ inputs.PATHS_TO_INVALIDATE }}'
