on:
  workflow_call:
    inputs:
      CHECK_IAM:
        type: boolean
        default: true
      branch:
        type: string
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true
jobs:
  Check-IAM:
    if: ${{ inputs.CHECK_IAM }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3      
    - name: Run validation
      uses:  mathem-se/iam-template-analyzer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ inputs.branch }}